auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  path_prefix: /loki

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 7d

chunk_store_config:
  max_look_back_period: 30s

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
