logging:
  level: info
  format: logfmt

loki:
  write:
    local:
      endpoint:
        url: "http://loki:3100/loki/api/v1/push"

discovery:
  docker:
    containers: {}

file:
  match:
    logs:
      path_targets: discovery.docker.containers.targets
      forward_to:
        - loki.write.local.receiver
