services:
  api:
    build:
      context: ./api
      tags:
        - josefkliment/api:latest
        - ghcr.io/josefkliment/api:latest
    image: josefkliment/api:latest
    container_name: api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./nginx
      tags:
        - josefkliment/frontend:latest
        - ghcr.io/josefkliment/frontend:latest
    image: josefkliment/frontend:latest
    container_name: frontend
    ports:
      - "7777:7777"
    volumes:
      - ./nginx/frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
