version: "3.8"
services:
  api:
    build:
      context: ./api
      tags:
        - josefkliment/api:latest
        - ghcr.io/klimejo22/api:latest
    image: josefkliment/api:latest
    container_name: api
    networks:
      - sentry_network
      - apiproject
    env_file:
      - envs/postgres.env
      - envs/api.env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c '
        uvicorn api:app --host 0.0.0.0 --port 8000 & 
        UVICORN_PID=$!;

        echo "Čekám na API, až bude ready...";
        until curl -sf http://localhost:8000/healthCheck; do
          echo -n ".";
          sleep 1;
        done;
        echo "\nAPI je ready, volám update endpoint...";
        curl -sf http://localhost:8000/update;

        wait $UVICORN_PID
      '
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthCheck"]
      interval: 3s
      timeout: 2s
      retries: 5

  frontend:
    build:
      context: ./nginx
      tags:
        - josefkliment/frontend:latest
        - ghcr.io/klimejo22/frontend:latest
    image: josefkliment/frontend:latest
    container_name: frontend
    networks:
      - sentry_network
      - apiproject
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
    volumes:
      - ./nginx/frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443"]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 5s

  postgres: 
    image: postgres:17
    container_name: postgres
    env_file:
      - envs/postgres.env
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: currencydata   
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    networks:
        - apiproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d currencydata -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
  # Grafana containery
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file:
      - envs/grafana.env
    # environment:
    #   - GF_SERVER_ROOT_URL=https://localhost:444/
    #   - GF_SECURITY_ADMIN_USER=admin
    #   - GF_SECURITY_ADMIN_PASSWORD=Abcdef0
    networks:
      - default
      - apiproject

    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki

  alloy:
    image: grafana/alloy:v1.8.3
    container_name: alloy
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy/alloy-config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    depends_on:
      - loki

volumes:
  pgdata:
  grafana_data:
  prometheus_data:
  loki_data:

networks:
  sentry_network:
    external: true
    name: sentry-self-hosted_default
  apiproject:
