version: "3.8"
services:
  api:
    build:
      context: ./api
      tags:
        - josefkliment/api:latest
        - ghcr.io/klimejo22/api:latest
    image: josefkliment/api:latest
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthCheck"]
      interval: 5s
      timeout: 2s
      retries: 5

  frontend:
    build:
      context: ./nginx
      tags:
        - josefkliment/frontend:latest
        - ghcr.io/klimejo22/frontend:latest
    image: josefkliment/frontend:latest
    container_name: frontend
    ports:
      - "7777:7777"
    volumes:
      - ./nginx/frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  postgres: 
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currencydata   
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d currencydata -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
  # Grafana containery
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Abcdef0
    networks:
      - default
    depends_on:
      - prometheus
      # - loki

  # loki:
  #   image: grafana/loki:2.9.3
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # alloy:
  #   image: grafana/alloy:latest
  #   container_name: alloy
  #   volumes:
  #     - ./alloy/config.alloy:/etc/alloy/config.yaml
  #     - /var/log:/var/log:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "7070:7070"
  #   command: run /etc/alloy/config.alloy  

volumes:
  pgdata:
  grafana_data:
  prometheus_data:
