{
 "title": "API dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errory z Dockeru",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\".+\"} |~ \"(?i)error|warn|fail|fatal|panic\" != \"level=info\""
    }
   ]
  },
  {
   "title": "Vsechny docker logy",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\".+\"}"
    }
   ]
  },
  {
   "title": "Dotazy na API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}